### PR TITLE
Fix (and test) codegen issues w/ types that conflict with Rust types inc `Result`

### LINKED ISSUE #568: Objects fields named Result generate code that (generally) won't compile
Having a `Result` definition seems to create code that won't compile, if `std::result::Result` is needed. 

## Reproduction

A simplified schema that shows the issue (note: if you don't have the enum, or something that needs a result, it won't give the error):

```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Test",
  "type": "object",
  "properties": {
    "results": {
      "$ref": "#/definitions/MultipleResult"
    }
  },
  "definitions": {
    "MultipleResult": {
      "type": "object",
      "properties": {
        "results": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Result"
          }
        }
      }
    },
    "Result": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        }
      }
    },
    "SomeEnum": {
      "type": "string",
      "description": "",
      "enum": [
        "Arm1",
        "Arm2",
        "Arm3"
      ]
    }
  }
}
```

<details>

<summary>
Gives:
</summary>

```rust
error[E0107]: struct takes 0 generic arguments but 2 generic arguments were supplied
   --> src/lib.rs:136:33
    |
136 |     fn try_from(value: &str) -> Result<Self, self::error::ConversionError> {
    |                                 ^^^^^^------------------------------------ help: remove these generics
    |                                 |
    |                                 expected 0 generic arguments
    |
note: struct defined here, with 0 generic parameters
   --> src/lib.rs:78:12
    |
78  | pub struct Result {
    |            ^^^^^^

error[E0107]: struct takes 0 generic arguments but 2 generic arguments were supplied
   --> src/lib.rs:142:36
    |
142 |     fn try_from(value: &String) -> Result<Self, self::error::ConversionError> {
    |                                    ^^^^^^------------------------------------ help: remove these generics
    |                                    |
    |                                    expected 0 generic arguments
    |
note: struct defined here, with 0 generic parameters
   --> src/lib.rs:78:12
    |
78  | pub struct Result {
    |            ^^^^^^

error[E0107]: struct takes 0 generic arguments but 2 generic arguments were supplied
   --> src/lib.rs:125:33
    |
125 |     fn from_str(value: &str) -> Result<Self, self::error::ConversionError> {
    |                                 ^^^^^^------------------------------------ help: remove these generics
    |                                 |
    |                                 expected 0 generic arguments
    |
note: struct defined here, with 0 generic parameters
   --> src/lib.rs:78:12
    |
78  | pub struct Result {
    |            ^^^^^^

error[E0053]: method `from_str` has an incompatible type for trait
   --> src/lib.rs:125:33
    |
125 |     fn from_str(value: &str) -> Result<Self, self::error::ConversionError> {
    |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |                                 |
    |                                 expected `Result<SomeEnum, ConversionError>`, found `Result`
    |                                 help: change the output type to match the trait: `std::result::Result<SomeEnum, ConversionError>`
    |
    = note: expected signature `fn(&_) -> std::result::Result<SomeEnum, ConversionError>`
               found signature `fn(&_) -> Result`

error[E0053]: method `try_from` has an incompatible type for trait
   --> src/lib.rs:136:33
    |
136 |     fn try_from(value: &str) -> Result<Self, self::error::ConversionError> {
    |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |                                 |
    |                                 expected `Result<SomeEnum, ConversionError>`, found `Result`
    |                                 help: change the output type to match the trait: `std::result::Result<SomeEnum, ConversionError>`
    |
    = note: expected signature `fn(&_) -> std::result::Result<SomeEnum, ConversionError>`
               found signature `fn(&_) -> Result`

error[E0053]: method `try_from` has an incompatible type for trait
   --> src/lib.rs:142:36
    |
142 |     fn try_from(value: &String) -> Result<Self, self::error::ConversionError> {
    |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |                                    |
    |                                    expected `Result<SomeEnum, ConversionError>`, found `Result`
    |                                    help: change the output type to match the trait: `std::result::Result<SomeEnum, ConversionError>`
    |
    = note: expected signature `fn(&std::string::String) -> std::result::Result<SomeEnum, ConversionError>`
               found signature `fn(&std::string::String) -> Result`

error[E0107]: struct takes 0 generic arguments but 2 generic arguments were supplied
   --> src/lib.rs:148:35
    |
148 |     fn try_from(value: String) -> Result<Self, self::error::ConversionError> {
    |                                   ^^^^^^------------------------------------ help: remove these generics
    |                                   |
    |                                   expected 0 generic arguments
    |
note: struct defined here, with 0 generic parameters
   --> src/lib.rs:78:12
    |
78  | pub struct Result {
    |            ^^^^^^

error[E0053]: method `try_from` has an incompatible type for trait
   --> src/lib.rs:148:35
    |
148 |     fn try_from(value: String) -> Result<Self, self::error::ConversionError> {
    |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |                                   |
    |                                   expected `Result<SomeEnum, ConversionError>`, found `Result`
    |                                   help: change the output type to match the trait: `std::result::Result<SomeEnum, ConversionError>`
    |
    = note: expected signature `fn(std::string::String) -> std::result::Result<SomeEnum, ConversionError>`
               found signature `fn(std::string::String) -> Result`

error[E0308]: mismatched types
   --> src/lib.rs:127:23
    |
125 |     fn from_str(value: &str) -> Result<Self, self::error::ConversionError> {
    |                                 ------------------------------------------ expected `Result` because of return type
126 |         match value {
127 |             "Arm1" => Ok(Self::Arm1),
    |                       ^^^^^^^^^^^^^^ expected `Result`, found `Result<SomeEnum, _>`
    |
    = note: `std::result::Result<SomeEnum, _>` and `Result` have similar names, but are actually distinct types
note: `std::result::Result<SomeEnum, _>` is defined in crate `core`
   --> /Users/colmanhumphrey/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:502:1
    |
502 | pub enum Result<T, E> {
    | ^^^^^^^^^^^^^^^^^^^^^
note: `Result` is defined in the current crate
   --> src/lib.rs:78:1
    |
78  | pub struct Result {
    | ^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
   --> src/lib.rs:137:9
    |
136 |     fn try_from(value: &str) -> Result<Self, self::error::ConversionError> {
    |                                 ------------------------------------------ expected `Result` because of return type
137 |         value.parse()
    |         ^^^^^^^^^^^^^ expected `Result`, found `Result<_, _>`
    |
    = note: `std::result::Result<_, _>` and `Result` have similar names, but are actually distinct types
note: `std::result::Result<_, _>` is defined in crate `core`
   --> /Users/colmanhumphrey/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:502:1
    |
502 | pub enum Result<T, E> {
    | ^^^^^^^^^^^^^^^^^^^^^
note: `Result` is defined in the current crate
   --> src/lib.rs:78:1
    |
78  | pub struct Result {
    | ^^^^^^^^^^^^^^^^^
help: consider using `Result::expect` to unwrap the `std::result::Result<_, _>` value, panicking if the value is a `Result::Err`
    |
137 |         value.parse().expect("REASON")
    |                      +++++++++++++++++

error[E0308]: mismatched types
   --> src/lib.rs:143:9
    |
142 |     fn try_from(value: &String) -> Result<Self, self::error::ConversionError> {
    |                                    ------------------------------------------ expected `Result` because of return type
143 |         value.parse()
    |         ^^^^^^^^^^^^^ expected `Result`, found `Result<_, _>`
    |
    = note: `std::result::Result<_, _>` and `Result` have similar names, but are actually distinct types
note: `std::result::Result<_, _>` is defined in crate `core`
   --> /Users/colmanhumphrey/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:502:1
    |
502 | pub enum Result<T, E> {
    | ^^^^^^^^^^^^^^^^^^^^^
note: `Result` is defined in the current crate
   --> src/lib.rs:78:1
    |
78  | pub struct Result {
    | ^^^^^^^^^^^^^^^^^
help: consider using `Result::expect` to unwrap the `std::result::Result<_, _>` value, panicking if the value is a `Result::Err`
    |
143 |         value.parse().expect("REASON")
    |                      +++++++++++++++++

error[E0308]: mismatched types
   --> src/lib.rs:149:9
    |
148 |     fn try_from(value: String) -> Result<Self, self::error::ConversionError> {
    |                                   ------------------------------------------ expected `Result` because of return type
149 |         value.parse()
    |         ^^^^^^^^^^^^^ expected `Result`, found `Result<_, _>`
    |
    = note: `std::result::Result<_, _>` and `Result` have similar names, but are actually distinct types
note: `std::result::Result<_, _>` is defined in crate `core`
   --> /Users/colmanhumphrey/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:502:1
    |
502 | pub enum Result<T, E> {
    | ^^^^^^^^^^^^^^^^^^^^^
note: `Result` is defined in the current crate
   --> src/lib.rs:78:1
    |
78  | pub struct Result {
    | ^^^^^^^^^^^^^^^^^
help: consider using `Result::expect` to unwrap the `std::result::Result<_, _>` value, panicking if the value is a `Result::Err`
    |
149 |         value.parse().expect("REASON")
    |                      +++++++++++++++++

Some errors have detailed explanations: E0053, E0107, E0308.
For more information about an error, try `rustc --explain E0053`.
error: could not compile `inspection-schema` (lib) due to 12 previous errors
```

</details>

## Solve

I think an explicit Result, like https://github.com/oxidecomputer/typify/pull/458/files, should hopefully solve it.

(meanwhile, I will probably change my field name...)

Thanks!

### PR DESCRIPTION
**Pull request by anelson**
I ran into oxidecomputer/typify#568 when trying to use typify to generate Rust bindings for the [Model Context
Protocol](https://spec.modelcontextprotocol.io). Anthropic have published a [JSON Schema specification for this protocol](https://github.com/modelcontextprotocol/specification/blob/main/schema/schema.json), but as soon as I tried to codegen Rust bindings for it, I ran into the aforementioned issue.

I added the entire MCP JSON schema to `typify/tests/schemas/model-context-protocol.json`, which as expected immediately caused the `schemas` test to fail.  Fixing this was a relatively simple matter of finding every place in the codegen that referred to the Rust `std::result::Result` type as simply `Result`, and modify the codegen to use the fully-qualified `::std::result::Result` type name instead.. That was enough to make the MCP schema work right.

But then I looked a bit closer and realized there were some other Rust built-in types that were being referenced in such a way as to cause either errors during codegen or generation of code that doesn't compile.

So I made a diabolical test schema `rust-collisions.json` that is truly cursed.  It defines a bunch of types that collide with Rust built-in types and keywords, and made the `schemas` test explode with such force that there may have been inquiries from the neighbors.  Upon reassuring them that that's just how the Rust compiler expresses affection, I made some more codegen changes to resolve all of the issues that my cursed schema exposed, by using fully-qualified type paths `::std::....` for every built-in Rust type that is referenced in the generated code.

I've tried to make the changes minimal, and to my knowledge none of the changes I have made would be breaking from the perspective of any user of the generated Rust code.

I had to modify several existing tests in `typify-impl` that broke because they were expecting the non-canonicalized versions of Rust standard types.  Pay particular attention to the [hack I put in `test_util::validate_output_impl`](https://github.com/anelson/typify/blob/e6be4468dcd88f3ae1c856132ead425080124bbb/typify-impl/src/test_util.rs#L95-L152) which is not something I'm particularly proud of but I think it retains the spirit of the test.

Closes #568

### CODE REVIEW

File: typify-impl/src/structs.rs [hunk 1]
```diff
@@ -373,12 +373,12 @@ pub(crate) fn generate_serde_attr(
     let default_fn = match (state, &prop_type.details) {
         (StructPropertyState::Optional, TypeEntryDetails::Option(_)) => {
             serde_options.push(quote! { default });
-            serde_options.push(quote! { skip_serializing_if = "Option::is_none" });
+            serde_options.push(quote! { skip_serializing_if = "std::option::Option::is_none" });
```
Comment (ahl) [inline typify-impl/src/structs.rs:376]: Should we prefix with :: ?

File: typify-impl/Cargo.toml [hunk 2]
```diff
@@ -17,7 +17,7 @@ schemars = "0.8.21"
 semver = "1.0.23"
 serde = "1.0.215"
 serde_json = "1.0.133"
-syn = { version = "2.0.89", features = ["full"] }
+syn = { version = "2.0.89", features = ["full", "visit-mut"] }
```
Comment (ahl) [inline typify-impl/Cargo.toml:20]: Is this new feature only needed for tests?

File: typify/tests/schemas.rs [hunk 3]
```diff
@@ -23,6 +23,8 @@ fn test_schemas() {
 }
 
 fn validate_schema(path: std::path::PathBuf) -> Result<(), Box<dyn Error>> {
+    println!("Testing the processing of schema: {}", path.display());
```
Comment (ahl) [inline typify/tests/schemas.rs:26]: Did you mean to leave this?

File: typify-impl/src/test_util.rs [hunk 4]
```diff
@@ -89,6 +92,57 @@ fn validate_output_impl<T: JsonSchema + Schema>(ignore_variant_names: bool) {
...
+    struct Visitor;
+
+    impl syn::visit_mut::VisitMut for Visitor {
+        fn visit_path_mut(&mut self, path: &mut syn::Path) {
+            // Check if path starts with ::std
+            if path.leading_colon.is_some()
+                && !path.segments.is_empty()
+                && path.segments[0].ident == "std"
+            {
+                // Fun additional hack to keep you on your toes:
```
Comment (ahl) [inline typify-impl/src/test_util.rs:121]: Can you check the history on that? It might have been during a previous round of prefixing

**Review by ahl — COMMENTED** [review]
Thanks for this. The short of it seems to be to prefix std types with their full path. Any other subtlety beyond the testing kludge?

**Comment by anelson** [comment]
> Thanks for this. The short of it seems to be to prefix std types with their full path. Any other subtlety beyond the testing kludge?

Yes that's pretty much the whole fix.  A few words to describe, and only +28,792 −13,699 lines to implement ;)

File: typify-impl/src/structs.rs (hunk 1 above)
Comment (anelson) [reply typify-impl/src/structs.rs:376]: Good catch, yes we should.  There's also a `std::vec::Vec` right below it which also needs to be fully qualified.

File: typify-impl/Cargo.toml (hunk 2 above)
Comment (anelson) [reply typify-impl/Cargo.toml:20]: Yes, good catch, I moved that feature to the `dev-dependencies`.

File: typify-impl/src/test_util.rs (hunk 4 above)
Comment (anelson) [reply typify-impl/src/test_util.rs:121]: Yes you are right, it was done in #647.

The tests that have the fully-qualified type paths in them don't seem wrong or irrelevant.  It's not a very common way to declare Rust types outside of proc macros and other codegen, but it's perfectly valid.  

I dislike the fact that a special-case is needed, and if anyone ever decides to extend those tests with a field with a fully-qualified type other than `HashMap<String, String>` then the tests will fail in a way that's probably going to be surprising.

On the other hand, it's actually not a realistic invariant that Rust -> JSON RPC -> Rust transform must always exactly reproduce the input Rust AST.  Codegen needs to fully-qualify types that would not normally be fully-qualified.  So another solution might be to run the decanonicalization pass on *both* `actual` and `expected`.  Now that I think of it, that seems like the better approach.  What do you think?

File: typify/tests/schemas.rs (hunk 3 above)
Comment (ahl) [reply typify/tests/schemas.rs]: If it was useful feel free to leave it

File: typify-impl/src/test_util.rs (hunk 4 above)
Comment (ahl) [reply typify-impl/src/test_util.rs:121]: I like the idea of running it on both actual and expected

Comment (anelson) [reply typify-impl/src/test_util.rs]: I just pushed https://github.com/oxidecomputer/typify/pull/705/commits/def217340862ddf63b4c1a3bbf00fc8b9af2f055 which does just that.  It's definitely better that way.

File: typify-impl/src/test_util.rs [hunk 5]
```diff
@@ -81,6 +88,10 @@ fn validate_output_impl<T: JsonSchema + Schema>(ignore_variant_names: bool) {
     assert!(!file.items.is_empty(), "{}", output.to_string());
     let actual = parse2::<DeriveInput>(file.items.first().unwrap().to_token_stream()).unwrap();
 
+    // Decanonicalize the types generated by typify so that we can compare them to the original
+    // Rust types' ASTs that definitely do not use canonicalized std types.
+    let actual = decanonicalize_std_types(actual);
+
     // Make sure they match.
     if let Err(err) = expected.syn_cmp(&actual, ignore_variant_names) {
```
Comment (ahl) [inline typify-impl/src/test_util.rs:96]: would another approach be to change the implementation of `impl SynCompare for TypePath` to be fuzzier i.e. to identify `::std::...::Foo` as equivalent to `Foo`?

Alternatively, I'm inclined towards changing the tests to just use the fully qualified type name.

What do you think of these options?

File: typify-impl/src/type_entry.rs [hunk 6]
```diff
@@ -1480,17 +1486,18 @@ impl TypeEntry {
...
                             D: ::serde::Deserializer<'de>,
                         {
-                            String::deserialize(deserializer)?
-                                .parse()
-                                .map_err(|e: self::error::ConversionError| {
-                                    <D::Error as ::serde::de::Error>::custom(
-                                        e.to_string(),
-                                    )
-                                })
+                            Self::try_from(
```
Comment (ahl) [inline typify-impl/src/type_entry.rs:1493]: I'd prefer we keep this as `parse()` -- I have some ambivalence about the use of To/From<String> in these cases.

Are there other instances (I may have missed) where there's a functional change?

**Review by ahl — COMMENTED** [review]
- how do we handle testing
- are there other functional changes (and if so, can we revert?)

model-context-protocol.json is large; is it adding value beyond what we get from rust-collisions?

Can you please take a look at rustdoc before and after? I don't recall if we'll see simplified or fully qualified types. The latter would be fine... but perhaps distracting / ugly.

Thanks.

**Comment by anelson** [comment]
> * how do we handle testing

Sorry, I don't understand what you're asking.  I added two additional schema test cases to exercise the problem and verify the fix.  They produce code that compiles and passes all existing tests for correctness.  Is there some additional testing you have in mind?

> * are there other functional changes (and if so, can we revert?)

I will revert the change to the `Deserialize` impl for `String` types.  There are no other such changes that I can see.

> model-context-protocol.json is large; is it adding value beyond what we get from rust-collisions?

It isn't needed to reproduce the problem with types named `Result`, no.  I added it initially to reproduce that bug, but I kept it there since it seems useful to have as a test case another real-world JSON schema, in case of regressions.  You already have the Github and Vega schemas, so I figured there was precedent.  I can remove it if you disagree.

> Can you please take a look at rustdoc before and after? I don't recall if we'll see simplified or fully qualified types. The latter would be fine... but perhaps distracting / ugly.

Sure.

I ran `cargo doc -p example-build` from this branch with my codegen changes.

This is the doc for `example_build::builder::Veggie`:

example_build::builder::Veggie docs

Looks fine to me.  The fully-qualified types are simplified in the output.  And yet the actual codegen output is still using the canonicalized output:

example_build::builder::Veggie Rust struct

File: typify-impl/src/type_entry.rs (hunk 6 above)
Comment (anelson) [reply typify-impl/src/type_entry.rs]: No that should be the only one.  I've reverted this in a subsequent commit.

**Comment by ahl** [comment]
> > * how do we handle testing
> 
> Sorry, I don't understand what you're asking. I added two additional schema test cases to exercise the problem and verify the fix. They produce code that compiles and passes all existing tests for correctness. Is there some additional testing you have in mind?

I should have been clearer; I was summarizing my code review feedback.

> I will revert the change to the `Deserialize` impl for `String` types. There are no other such changes that I can see.

Thanks!

> > model-context-protocol.json is large; is it adding value beyond what we get from rust-collisions?
> 
> It isn't needed to reproduce the problem with types named `Result`, no. I added it initially to reproduce that bug, but I kept it there since it seems useful to have as a test case another real-world JSON schema, in case of regressions. You already have the Github and Vega schemas, so I figured there was precedent. I can remove it if you disagree.

I'm just a little reluctant to extend testing time (etc.) if there's not a ton of value; please think it over and do what you think is best.

> > Can you please take a look at rustdoc before and after? I don't recall if we'll see simplified or fully qualified types. The latter would be fine... but perhaps distracting / ugly.
> 
> Sure.
> 
> I ran `cargo doc -p example-build` from this branch with my codegen changes.

Thanks for checking on that!

File: typify-impl/src/test_util.rs (hunk 5 above)
Comment (ahl) [reply typify-impl/src/test_util.rs:96]: > Yes I suppose you could change the `SynCompare` impl to strip path components any time it sees `::std::` before the comparison. My personal preference is to not do that, since it's more spooky action at a distance, while this impl is very explicit about what's happening.

Fair enough.

> That would certainly work, but if anyone adds new test cases will they remember that the types have to be fully-qualified, and if they forget will the resulting test failure make it obvious what their mistake was?

I think so.

> It's your codebase, your call, but speaking in terms of my personal preference, I prefer the explicit decanonicalization approach.

Let's go with your approach.

**Comment by anelson** [comment]
I just noticed in my comment https://github.com/oxidecomputer/typify/pull/705#issuecomment-2512300833, I just happened to pick at random one of the generated builder structs, and there is a `String` that is not canonicalized!

I looked into it further, it appears that `schemas.rs` never enabled generating struct builders!  I've just made another change to enable struct builders for all schemas.  As soon as I did that, the tests started to fail when generating builders for my cursed schema, so then I fixed the struct builder generator output to properly canonicalize `String`.

Note that as a result of this, the generated code for the test case `merged-schemas` compiles with warnings:

```

WARNINGS:
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
warning: unused variable: `value`
    --> tests/schemas/merged-schemas.rs:1825:13
     |
1825 |             value: Unsatisfiable2,
     |             ^^^^^ help: if this is intentional, prefix it with an underscore: `_value`
     |
     = note: `#[warn(unused_variables)]` on by default

warning: unused variable: `value`
    --> tests/schemas/merged-schemas.rs:1831:17
     |
1831 |         fn from(value: super::Unsatisfiable2) -> Self {
     |                 ^^^^^ help: if this is intentional, prefix it with an underscore: `_value`

warning: unused variable: `value`
    --> tests/schemas/merged-schemas.rs:1846:13
     |
1846 |             value: Unsatisfiable3,
     |             ^^^^^ help: if this is intentional, prefix it with an underscore: `_value`

warning: unused variable: `value`
    --> tests/schemas/merged-schemas.rs:1852:17
     |
1852 |         fn from(value: super::Unsatisfiable3) -> Self {
     |                 ^^^^^ help: if this is intentional, prefix it with an underscore: `_value`

warning: 4 warnings emitted
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈

STDERR:
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
warning: unused variable: `value`
    --> /Users/rupert/sources/typify/typify/tests/schemas/merged-schemas.rs:1825:13
     |
1825 |             value: Unsatisfiable2,
     |             ^^^^^ help: if this is intentional, prefix it with an underscore: `_value`
     |
     = note: `#[warn(unused_variables)]` on by default

warning: unused variable: `value`
    --> /Users/rupert/sources/typify/typify/tests/schemas/merged-schemas.rs:1831:17
     |
1831 |         fn from(value: super::Unsatisfiable2) -> Self {
     |                 ^^^^^ help: if this is intentional, prefix it with an underscore: `_value`

warning: unused variable: `value`
    --> /Users/rupert/sources/typify/typify/tests/schemas/merged-schemas.rs:1846:13
     |
1846 |             value: Unsatisfiable3,
     |             ^^^^^ help: if this is intentional, prefix it with an underscore: `_value`

warning: unused variable: `value`
    --> /Users/rupert/sources/typify/typify/tests/schemas/merged-schemas.rs:1852:17
     |
1852 |         fn from(value: super::Unsatisfiable3) -> Self {
     |                 ^^^^^ help: if this is intentional, prefix it with an underscore: `_value`
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
```

I'm not sure if this is considered acceptable for the generated code or not.  It does not appear to be caused by any of my changes, it's just coming to light now that I've enabled generating builder structs in the test case.  To confirm this, I checked out `main`, added `.with_struct_builder(true)` to the `schemas.rs` test, and re-ran the tests; I get the same warnings.  It seems like it's an issue outside the scope of this PR but maybe you disagree.

**Comment by anelson** [comment]
> I'm just a little reluctant to extend testing time (etc.) if there's not a ton of value; please think it over and do what you think is best.

I did some testing (all on my local M1 Pro MBP).

## `main` branch (without any of my test changes)

Right after a `cargo clean`:

```
cargo test -p typify  136.85s user 17.49s system 357% cpu 43.130 total
```

Re-running `cargo test` (so no rebuild, just re-running the already-built tests):

```
cargo test -p typify  4.89s user 3.62s system 73% cpu 11.540 total
```

## this branch with my changes

Right after a `cargo clean`:

```
cargo test -p typify  140.43s user 17.88s system 279% cpu 56.583 total
```

Re-running `cargo test` (so no rebuild, just re-running the already-built tests):

```
cargo test -p typify  5.67s user 3.98s system 73% cpu 13.050 total
```

## this branch with my changes, but with the MCP schema removed

Right after a `cargo clean`:

```
cargo test -p typify  135.65s user 17.23s system 348% cpu 43.851 total
```

Re-running `cargo test` (so no rebuild, just re-running the already-built tests):

```
cargo test -p typify  5.30s user 4.03s system 72% cpu 12.929 total
```

Key findings:

- The changes increase clean build time by 31.2% (+13.5s)
- The MCP schema accounts for most of this increase (12.7s)
- Test re-runs are marginally slower (+13.1%, or 1.5s)

So I don't think the MCP schema is providing enough value to justify the increase in build/test time.  I'll remove it.

File: typify/tests/schemas.rs [hunk 7]
```diff
@@ -64,7 +64,8 @@ fn validate_schema(path: std::path::PathBuf) -> Result<(), Box<dyn Error>> {
                 "std",
                 typify::CrateVers::Version("1.0.0".parse().unwrap()),
                 None,
-            ),
+            )
+            .with_struct_builder(true),
```
[the remark this answers is not in the document]
Comment (anelson) [reply typify/tests/schemas.rs:68]: See, see my comment https://github.com/oxidecomputer/typify/pull/705#issuecomment-2512335987 for a detailed explanation.  There was one place left in the codegen where `String` was used, and all of the tests passed because that one place was in the codegen for optional struct builders.  So I enabled that for all of the schema tests, the tests started to fail, then I fixed that one remaining use of a simple `String` type and verified that the tests passed.  I left this in place because it seems like these tests are meant to exercise the code generation in its entirety.

File: typify-impl/src/test_util.rs [hunk 8]
```diff
@@ -104,18 +104,16 @@ fn validate_output_impl<T: JsonSchema + Schema>(ignore_variant_names: bool) {
...
-/// The code generation logic that generates Rust bindings given JSON Schema always canonicalizes
+/// Our code generation logic, always canonicalizes
 /// any standard type (eg, `Option` is output as `::std::option::Option`), to avoid potential
 /// conflicts with types in the JSON schema with conflicting names like `Option`.  Unfortunately,
-/// this complicates the test cases that start with a Rust type that implements `JsonSchema`, use
-/// that to generate a JSON schema for that type, then use typify to generate a Rust binding for
-/// that type, and expects that the Rust AST for the source type and the generated type are exactly
-/// the same.
+/// this complicates the test cases that validate that a round-trip from Rust to JSON back to Rust
+/// are exactly the same.
```
Comment (ahl) [inline typify-impl/src/test_util.rs]: wrap, remove comma

**Review by ahl — APPROVED** [review]
one fix, merge Cargo.toml, and we'll merge

File: typify-impl/src/test_util.rs (hunk 8 above)
Comment (anelson) [reply typify-impl/src/test_util.rs]: I rewrapped and removed the extraneous comma.  

I rebased against upstream `main` to resolve the conflict with `Cargo.toml`.

Hopefully this is good to go now...

**Comment by ahl** [comment]
Thanks so much for this contribution! Greatly appreciated!
