### PR TITLE
Fix panic with non-zero integers, nullable types, and default values

### LINKED ISSUE #770: nullable NonZeroU* default result in an internal panic
```json
    "MrDefaultNumbers": {
      "type": "object",
      "properties": {
        "big_nullable": {
          "type": [
            "integer",
            "null"
          ],
          "format": "uint64",
          "minimum": 1,
          "default": 1
        }
      }
```

results in

```
thread 'test_schemas' panicked at typify-impl/src/value.rs:168:31:
internal error: entered unreachable code
stack backtrace:
   0: rust_begin_unwind
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:146:5
   3: typify_impl::value::<impl typify_impl::type_entry::TypeEntry>::output_value
             at /Users/ahl/src/typify/typify-impl/src/value.rs:168:31
   4: typify_impl::value::<impl typify_impl::type_entry::TypeEntry>::output_value
             at /Users/ahl/src/typify/typify-impl/src/value.rs:71:33
   5: typify_impl::defaults::<impl typify_impl::type_entry::TypeEntry>::default_fn
             at /Users/ahl/src/typify/typify-impl/src/defaults.rs:358:25
   6: typify_impl::structs::generate_serde_attr
             at /Users/ahl/src/typify/typify-impl/src/structs.rs:415:17
   7: typify_impl::type_entry::TypeEntry::output_struct::{{closure}}
             at /Users/ahl/src/typify/typify-impl/src/type_entry.rs:1130:39
   8: <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::for_each
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/slice/iter/macros.rs:252:21
   9: typify_impl::type_entry::TypeEntry::output_struct
             at /Users/ahl/src/typify/typify-impl/src/type_entry.rs:1117:9
  10: typify_impl::type_entry::TypeEntry::output
             at /Users/ahl/src/typify/typify-impl/src/type_entry.rs:712:17
  11: typify_impl::TypeSpace::to_stream::{{closure}}
             at /Users/ahl/src/typify/typify-impl/src/lib.rs:904:36
  12: core::iter::traits::iterator::Iterator::for_each::call::{{closure}}
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/iter/traits/iterator.rs:815:29
  13: core::iter::traits::iterator::Iterator::fold
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/iter/traits/iterator.rs:2589:21
  14: core::iter::traits::iterator::Iterator::for_each
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/iter/traits/iterator.rs:818:9
  15: typify_impl::TypeSpace::to_stream
             at /Users/ahl/src/typify/typify-impl/src/lib.rs:902:9
  16: <typify_impl::TypeSpace as quote::to_tokens::ToTokens>::to_tokens
             at /Users/ahl/src/typify/typify-impl/src/lib.rs:1008:23
  17: schemas::validate_schema
             at ./tests/schemas.rs:89:16
  18: schemas::test_schemas
             at ./tests/schemas.rs:20:9
  19: schemas::test_schemas::{{closure}}
             at ./tests/schemas.rs:14:18
  20: core::ops::function::FnOnce::call_once
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/ops/function.rs:250:5
  21: core::ops::function::FnOnce::call_once
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

The issue is this code:

https://github.com/oxidecomputer/typify/blob/eed9bee494c3421b194e5d078cd9c9520ef8bb3c/typify-impl/src/value.rs#L161-L171

Note that we assume that the type name is a valid numerical suffix... but it is not! We also support `NonZeroU64` e.g. in this schema.

### PR DESCRIPTION
**Pull request by ahl**
Fixes #770

### CODE REVIEW

File: typify-impl/src/value.rs [hunk 1]
```diff
@@ -162,12 +163,21 @@ impl TypeEntry {
...
+                        #type_path::new(#num).unwrap()
+                    }
+                } else {
+                    let val =
+                        match proc_macro2::Literal::from_str(&format!("{}_{}", value, type_name)) {
+                            Ok(v) => v,
+                            Err(_) => unreachable!(),
+                        };
+                    TokenStream::from(proc_macro2::TokenTree::from(val))
+                }
```
Comment (ahl) [inline typify-impl/src/value.rs:180]: actual fix

File: typify/tests/schemas/types-with-defaults.json [hunk 2]
```diff
@@ -74,8 +74,17 @@
...
           "default": 3
+        },
+        "big_nullable": {
+          "type": [
+            "integer",
+            "null"
+          ],
+          "format": "uint64",
+          "minimum": 1,
+          "default": 1
```
Comment (ahl) [inline typify/tests/schemas/types-with-defaults.json:85]: new test case

File: typify/tests/schemas/types-with-defaults.rs [hunk 3]
```diff
@@ -527,23 +557,29 @@ pub mod builder {
...
+            "\"1970-01-01T00:00:00Z\"",
+        )
+        .unwrap()
     }
-    pub(super) fn doodad_when() -> chrono::DateTime<chrono::offset::Utc> {
-        serde_json::from_str::<chrono::DateTime<chrono::offset::Utc>>("\"1970-01-01T00:00:00Z\"")
-            .unwrap()
+    pub(super) fn mr_default_numbers_big_nullable() -> ::std::option::Option<::std::num::NonZeroU64>
+    {
+        ::std::option::Option::Some(::std::num::NonZeroU64::new(1).unwrap())
```
Comment (ahl) [inline typify/tests/schemas/types-with-defaults.rs:573]: new default value

File: typify-impl/src/value.rs [hunk 4]
```diff
@@ -162,12 +163,21 @@ impl TypeEntry {
...
-                    Ok(v) => v,
-                    Err(_) => unreachable!(),
-                };
-                TokenStream::from(proc_macro2::TokenTree::from(val))
+                if type_name.starts_with(STD_NUM_NONZERO_PREFIX) {
+                    let type_path = syn::parse_str::<syn::TypePath>(type_name).unwrap();
+                    let num = proc_macro2::Literal::from_str(value.to_string().as_str()).unwrap();
+
+                    quote! {
+                        #type_path::new(#num).unwrap()
```
Comment (bnaecker) [inline typify-impl/src/value.rs:171]: Not a huge deal but, if you've already validated the `value`, then you could use `new_unchecked()` here to avoid the unwrap. I can't tell if you've validated it though.

Comment (ahl) [reply typify-impl/src/value.rs:171]: I considered that, but didn't want to generate

```rust
    unsafe { #type_path::new_unchecked(#num) }
```
