### PR TITLE
Various improvement to enums, arrays, and `deny_unknown_fields`

### LINKED ISSUE #280: deny_unknown_fields on a oneOf enum prevents use of flattened additionalProperties
When a subschema uses a oneOf where one variant uses additionalProperties, all objects fail to deserialize claiming that there is no matching variant for the generated untagged enum. Upon inspection, it seems like during a successful generation, the deny_additional_fields attribute is added to the object, which is [documented to not play nicely with the flatten attribute](https://serde.rs/container-attrs.html#deny_unknown_fields). Note that this behavior is not consistently seen on all such enums, so it might be an edge case with my example specifically. Adding an explicit `"additionalProperties": true` on the object causes generation to fail.

Sample schema fragment:
```json
"References": {
    "oneOf": [
        { 
            "$comment": "An array of mod names. Version is inferred to be @modlinks." ,
            "type": "array", 
            "items": { "type": "string" }
        },
        { 
            "$comment": "Mapping of mod name to the desired version",
            "type": "object", 
            "additionalProperties": 
            { 
                "oneOf": [
                    { "$ref": "#/definitions/StringVersion" },
                    { "$ref": "#/definitions/ReferenceDef" }
                ]
            }
        }
    ]
}
```

The corresponding generated Rust code is:
```rs
#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(untagged, deny_unknown_fields)] //problem is here, because Variant1.extra is flattened
pub enum References {
    Variant0(Vec<String>),
    Variant1 {
        #[serde(flatten)]
        extra: std::collections::HashMap<String, ReferencesVariant1ExtraValue>,
    },
}
```

### PR DESCRIPTION
**Pull request by ahl**
Fix (and simplify) enum variant construction by converting the schema to a type and then subsuming that type into the variant.

Avoid using serde's deny_unknown_fields with serde's flatten... with which it is incompatible.

Significantly improve handling of various tuple-generating types (only a few trivial cases were handled).

Correct handling of singleton (one-element) tuples which require a tailing comma in order to be treated as tuples (rather than merely as extraneously parenthesized types).

Closes #280 and #244

### CODE REVIEW

File: typify-impl/src/type_entry.rs [hunk 1]
```diff
@@ -1597,9 +1608,10 @@ impl TypeEntry {
         match &self.details {
             // We special-case enums for which all variants are simple to let
             // them be passed as values rather than as references.
-            TypeEntryDetails::Enum(TypeEntryEnum{ variants, .. })
-                // TODO we should probably cache this rather than iterating
```
Comment (ahl) [inline typify-impl/src/type_entry.rs:1601]: the placement of this comment was causing rustfmt to ... give up!
